### ISSUE TITLE
Carl's review points

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-ftbs-rats-msg-wrap#14]
* In the third sentence of intro, message should be plural
* The definition of RFC6838 in the CDDL looks to be incomplete
* Re: suffixes, I was assuming certificate extension support would use the DER/BER values. What about CRL extensions? Is PEM needed as well?
* The structured suffix link in Section 3.1 is broken.
* Maybe reference EAT media types spec as initial values of interest.

**Comment by thomas-fossati** [comment]
* [x] In the third sentence of intro, message should be plural
* [x] The definition of RFC6838 in the CDDL looks to be incomplete
* [x] The structured suffix link in Section 3.1 is broken.
* [x] Maybe reference EAT media types spec as initial values of interest.

> Re: suffixes, I was assuming certificate extension support would use the DER/BER values. What about CRL extensions? Is PEM needed as well?

I am not sure I understand.  I'll seek clarification from Carl on the list.

**Comment by thomas-fossati** [comment]
The leftover point is tracked in #18

**Comment by carl-wallace** [comment]
I was asking how the enumerated list of suffixes (in the -01 draft) applied to certificates and CRLs. I was assuming that ber/der signified certificates and was asking if something was needed for CRLs and whether or not PEM support was necessary. Upon re-reading, the ber/der assumption was wrong (the suffix is more general than certificates). Whether or not PEM is needed may be worth considering but it's not really relevant to this draft. I'd just ignore that comment.
