### ISSUE TITLE
CWT/JWT registries for an unsigned CMW

### ISSUE THREAD

**Issue by nedmsmith** [thomas-fossati/draft-ftbs-rats-msg-wrap#31]
CMWs aren't necessarily signed which means the CMW could be included inside of a signed container. For example, a CMW certificate extension allows the CMW to be signed via an X.509 certificate.

A CWT is also a signed container that could contain a CMW. However, there isn't a CWT registry entry for CMW.

This issue proposes adding an IANA Considerations section:

IANA is requested to allocate the following tags in the "CWT Claims" registry, preferably with the specific CWT Claim value requested:

| Claim Name | Claim Description              | JWT Claim Name  | Claim Key | Claim Value Type                                             | Change Controller       | Reference                |       
| ------------ | ------------------------- | ------------------ | ---------- | ------------------------------------------- | ------------------------ | ------------------- |
|     cmw         | A CMW , see {{&SELF}}    |           cmw              |        11        | JSON Array, or CBOR Array, or CBOR Tag    | [IESG]                      | [this specification ] |

**Comment by nedmsmith** [comment]
The CWT registry identifies the contents as either a CBOR array or CBOR tag as described in sections 4.2 and 4.3 respectively.

The JWT registry identifies the contents as a JSON array.

**Comment by thomas-fossati** [comment]
Fixed in #33
